# Generated by Django 5.1.3 on 2024-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedcandidatetimeline',
            name='timeline_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
