# Generated by Django 5.1.3 on 2024-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_candidateeducation_candidateproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateproject',
            name='project_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
