# Generated by Django 5.1.3 on 2024-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_rename_timeline_comment_shortlistedcandidatetimeline_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='status_in_interview',
            field=models.CharField(blank=True, choices=[('Initial Communication', 'Initial Communication'), ('HR Screening/Preliminary Interview', 'HR Screening/Preliminary Interview'), ('Coordination for Technical/Functional Rounds', 'Coordination for Technical/Functional Rounds'), ('Feedback and Follow-Up', 'Feedback and Follow-Up'), ('Final Interview', 'Final Interview'), ('Offer Rollout', 'Offer Rollout'), ('Post-Interview Process', 'Post-Interview Process'), ('Rejected', 'Rejected')], max_length=225, null=True),
        ),
    ]
