# Generated by Django 5.1.3 on 2024-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_candidateprofile_status_in_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='status_in_interview',
            field=models.CharField(blank=True, choices=[('Shortlisted', 'Shortlisted'), ('Initial Communication', 'Initial Communication'), ('HR Screening/Preliminary Interview', 'HR Screening/Preliminary Interview'), ('Coordination for Technical/Functional Rounds', 'Coordination for Technical/Functional Rounds'), ('Feedback and Follow-Up', 'Feedback and Follow-Up'), ('Final Interview', 'Final Interview'), ('Offer Rollout', 'Offer Rollout'), ('Post-Interview Process', 'Post-Interview Process'), ('Rejected', 'Rejected')], default='Shortlisted', max_length=225, null=True),
        ),
    ]
