# Generated by Django 5.1.3 on 2024-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_candidateprofile_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
