# Generated by Django 5.1.3 on 2024-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_candidateeducation_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='startingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
