# Generated by Django 5.1.3 on 2024-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_candidateprofile_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_live_job_post',
            field=models.BooleanField(default=True),
        ),
    ]
