# Generated by Django 5.1.3 on 2024-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_jobposting_is_live_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
