# Generated by Django 5.1.3 on 2024-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_alter_shortlistedcandidate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
