# Generated by Django 5.1.3 on 2024-12-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_companyprofileviewpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=5),
        ),
    ]
