# Generated by Django 5.1.3 on 2024-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_rejectedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedcandidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
