# Generated by Django 5.1.3 on 2024-12-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_reasontorejectcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='media/candidate-resume'),
        ),
    ]
