# Generated by Django 5.1.3 on 2024-12-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_alter_candidateprofile_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='last_ctc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
