# Generated by Django 5.1.3 on 2024-12-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_candidateprofile_last_ctc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='last_ctc',
            new_name='ctc',
        ),
    ]
