# Generated by Django 5.1.3 on 2024-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0021_alter_candidateprofile_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
